services:
  bankdb:
    image: mongo:8.0.1
    container_name: bankdb
    ports:
      - "27017:27017"
    volumes:
      - ./database/data/db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - bank-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: "3"
    restart: unless-stopped

  redis:
    image: redis:7.0.5
    container_name: bankredis
    ports:
      - "6379:6379"
    networks:
      - bank-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  vite:
    build:
      context: ./frontend/bankfrontend/
      dockerfile: Dockerfile
    container_name: bankvite
    ports:
      - "3000:3000"
    networks:
      - bank-network
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend/bankfrontend/dist:/app/dist
    command: ["serve", "-s", "dist", "-l", "3000"]

networks:
  bank-network:
    driver: bridge